---

- hosts: all
  become: true
  tasks:

  - name: Debian - install apache and php packages
    package:
      name:
        - apache2 
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: RHEL - install apache and php packages
    package:
      name:
        - httpd 
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"
