---

 - hosts: all
   become: true
   pre_tasks:

   - name: update repository index (RHEL)
     tags: always
     dnf:
       update_cache: yes
     when: ansible_distribution == "RedHat"

   - name: update repository index (Debian/Ubuntu)
     tags: always
     apt:
       update_cache: yes
     when: ansible_distribution in ["Ubuntu", "Debian"]

 - hosts: all
   become: true
   roles:
     - base
       
 - hosts: workstations
   become: true
   roles:
     - workstations
     
 - hosts: web_servers
   become: true
   roles:
     - web_servers
     
 - hosts: db_servers
   become: true
   roles:
     - db_servers
     
 - hosts: file_servers
   become: true
   roles:
     - file_servers     
