---

 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (RHEL)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "RedHat"

   - name: install updates (Debian/Ubuntu)
     tags: always     
     apt:
       upgrade: yes
       update_cache: yes
     when: ansible_distribution in ["Ubuntu", "Debian"]

 - hosts: zima
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
 
   - name: install apache and php for RedHat servers
     tags: apache,httpd,redhat
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "RedHat"
