- name: install mariadb server package (RHEL)
  tags: rhel,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"
    
- name: install mariadb server package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]
